### ISSUE TITLE
in rc.lua, hints.init() should be placed after the beautiful.init()

### ISSUE THREAD

**Issue by guotsuan** [zackpete/hints#1]
Hi,  
Thank for this really useful module.  I think it is may be too trivial to mention that
probably in the document, you could be specific that the hints.init() should be placed after the beautiful.init() in the rc.lua. 

It may help the some the newbies like me :)

Best regards,

Quan

**Comment by zackpete** [comment]
Thanks for the heads up, I updated the readme.
-zack
